// <auto-generated />
namespace FoodOrder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new112w3s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new112w3s));
        
        string IMigrationMetadata.Id
        {
            get { return "201910190944009_new112w3s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
